# Modified from https://github.com/andreoliwa/nitpick/blob/develop/src/nitpick/resources/python/pylint.toml
["pyproject.toml".tool.poetry.dependencies]
pylint = {version = "*", optional = true}

["pyproject.toml".tool.poetry.extras]
lint = ["pylint"]

[".pylintrc".MASTER]
jobs = 1
extension-pkg-whitelist = "pydantic"

[".pylintrc".REPORTS]
output-format = "colorized"

[".pylintrc"."MESSAGES CONTROL"]
disable = "bad-continuation,bad-whitespace,fixme,cyclic-import,line-too-long"

[".pylintrc".BASIC]
good-names = "i,j,k,e,ex,Run,_,id,rv,c"

[".pylintrc".FORMAT]
max-line-length = 110
max-module-lines = 1000
indent-after-paren = 4

[".pylintrc".DESIGN]
max-attributes=12
max-args=7

[".pylintrc".SIMILARITIES]
min-similarity-lines = 4
ignore-comments = "yes"
ignore-docstrings = "yes"
ignore-imports = "no"

[".pylintrc".VARIABLES]
dummy-variables-rgx = "_$|dummy"
